services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clean_arq
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3307:3306"  # A porta externa 3307 é mapeada para a porta interna 3306
    environment:
      MYSQL_ROOT_PASSWORD: root  # Define a senha do usuário root
      MYSQL_DATABASE: clean_arq # Cria automaticamente o banco de dados "clean_arq"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
